services:
  ubuntu58:
    build:
      dockerfile: ./Dockerfile
    ports: 
      - "8080:80"
    networks:
      anetwork:
        ipv4_address: 10.5.0.5
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app


  mariadb:
    image: mariadb:10.11.6
    environment:
      - MYSQL_DATABASE=testdb
      #- MYSQL_ROOT_PASSWORD=testpass
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - "3306:3306"
    networks:
      anetwork:
        ipv4_address: 10.5.0.6

networks:
  anetwork:
     driver: bridge
     ipam:
       config:
         - subnet: 10.5.0.0/16


