services:
  nginx:
    image: nginx:latest
    ports: 
      - "8080:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app
   
  phpfpm:
    build:
      dockerfile: ./php/Dockerfile
    environment:
      #- mysql_user="root"
      - mysql_user=root
      - mysql_port=3306
      - mysql_db=testdb
      - mysql_user_pass=testpass
    volumes:
      - ./app:/app

  mysql:
    build:
      dockerfile: ./mysql/Dockerfile
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=testpass
    ports:
      - "8081:3306"


  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password

      