version: '3'
services:
  server-1:
    image: php:8.1-fpm-alpine
    environment:
      test: 1
    restart: always
    volumes:
      - ./app:/app

  server-2:
    image: php:8.1-fpm-alpine
    environment:
      test: 2
    restart: always
    volumes:
      - ./app:/app

  server-3:
    image: php:8.1-fpm-alpine
    environment:
      test: 3
    restart: always
    volumes:
      - ./app:/app

  nginx:
    image: nginx
    ports:
      - 9999:9999
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - ./app:/app